version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=QetaGhyarDb;User=sa;Password=P@$$w0rd;TrustServerCertificate=True;
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    networks:
      - backend-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "4200:80"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
